apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  configOverrides:
    server:
      - confluent.balancer.enable=true
  dataVolumeCapacity: 1Gi
  image:
    application: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/confluentinc/cp-server:7.7.1"
    init: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/confluentinc/confluent-init-container:2.9.3"
  replicas: 1
  storageClass:
    name: gp2
  podTemplate:
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests: 
        cpu: 2
        memory: 1Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                  - confluent
