apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: confluent-scc
allowPrivilegedContainer: false
allowedCapabilities: []
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowedFlexVolumes: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1001
    max: 1005
groups:
  - system:authenticated
priority: 10
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1005
seccompProfiles:
  - runtime/default
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
