name: Sync Confluent Images to ECR

on:
  schedule:
    - cron: "0 2 * * *"  # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    env:
      REPO_API: "https://api.github.com/repos/confluentinc/confluent-kubernetes-examples/contents/general/cp-version"
      LAST_SEEN_FILE: "last_seen_sha.txt"
      AWS_REGION: "<your-aws-region>"
      AWS_ACCOUNT_ID: "<your-aws-account-id>"
      ECR_REPO_PREFIX: "<your-ecr-repo-prefix>"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq skopeo curl

      - name: Get last seen SHA
        id: last_seen
        run: |
          if [ -f "$LAST_SEEN_FILE" ]; then
            cat $LAST_SEEN_FILE
          else
            touch $LAST_SEEN_FILE
          fi

      - name: List files from GitHub
        run: |
          curl -s $REPO_API | jq -r '.[] | select(.name | test("confluent-platform-kraft-.*\\.yaml")) | "\(.name) \(.sha) \(.download_url)"' > files_list.txt

      - name: Find new files
        run: |
          awk 'NR==FNR{seen[$2]; next} !($2 in seen)' "$LAST_SEEN_FILE" files_list.txt > new_files.txt
          echo "Found new files:"
          cat new_files.txt

      - name: Process new files and copy images
        run: |
          while read -r file sha url; do
            echo "Processing $file"
            curl -s -O "$url"

            IMAGES=$(yq eval '.spec.template.spec.containers[].image' "$file")
            for image in $IMAGES; do
              IMAGE_NAME=$(basename $image)
              TARGET_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PREFIX/$IMAGE_NAME"
              skopeo copy --insecure-policy docker://$image docker://$TARGET_IMAGE
            done
          done < new_files.txt

      - name: Update last seen SHA
        run: cp files_list.txt $LAST_SEEN_FILE && git add $LAST_SEEN_FILE && git commit -m "Update last seen SHA" && git push
